# Generated by Django 3.0.6 on 2020-05-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatsby_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=500)),
            ],
        ),
    ]
