# Generated by Django 3.0.6 on 2020-05-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatsby_blog', '0002_blogsubscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogLikes',
            new_name='BlogLike',
        ),
        migrations.RenameModel(
            old_name='BlogSubscribers',
            new_name='BlogSubscriber',
        ),
    ]
